[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  me-no-dev/ESPAsyncWebServer @ ^1.2.3
  me-no-dev/AsyncTCP @ ^1.1.1
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^3.11.0
build_flags =
  -DWEB_ENABLED=1
  -Iinclude
src_dir = .
src_filter = +<alkalinity_monitor_v2_1.ino>
